ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'UGX';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS exchange_rate DECIMAL(10, 6);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS original_amount DECIMAL(12, 2);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS original_currency VARCHAR(3);
